import * as Dialog from '@radix-ui/react-dialog';
import { useState, useEffect, useMemo } from 'react';
import { X, Package, ExternalLink } from 'lucide-react';
import { lotsAPI } from '../../../services/lots.api';
import { purchaseSummaryAPI } from '../../../services/purchaseSummary.api';
import { riceCodesAPI } from '../../../services/riceCodes.api';
import { LoadingSpinner } from '../../admin/shared/LoadingSpinner';
import { EmptyState } from '../../admin/shared/EmptyState';
import { getRiceTypeLabel } from '../../../utils/riceType';
import type {
  InwardSlipPass,
  Lot,
  Kaanta,
  RiceCode,
  RiceType,
  PurchaseSummaryLotDetail,
} from '../../../types/entities';
import {
  getTruncatedLotNumberForDisplay,
  getLotSerialNumberInFullPurchasesList,
  isAutoGeneratedKaantaLot,
} from '../../../utils/purchasesLotsDisplay';

interface LinkedLotsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  isp: InwardSlipPass | null;
  /** Optional godown scope — matches purchase-summary `godown_id` (e.g. ISP list filter). */
  godownId?: string;
}

function mergeById<T extends { id: string }>(rows: T[]): T[] {
  const map = new Map<string, T>();
  for (const row of rows) {
    map.set(row.id, row);
  }
  return [...map.values()];
}

export function LinkedLotsDialog({ open, onOpenChange, isp, godownId }: LinkedLotsDialogProps) {
  /** Kaanta-linked lots only (purchase-summary), merged across saudas on this ISP */
  const [lots, setLots] = useState<PurchaseSummaryLotDetail[]>([]);
  /** Same array as `GET /lots` (no filters) — used for S. No. matching the Lots page */
  const [fullLotsList, setFullLotsList] = useState<Lot[]>([]);
  const [kaantas, setKaantas] = useState<Kaanta[]>([]);
  const [riceCodes, setRiceCodes] = useState<RiceCode[]>([]);
  const [riceTypes, setRiceTypes] = useState<RiceType[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (open && isp) {
      fetchData();
    }
  }, [open, isp, godownId]);

  const fetchData = async () => {
    if (!isp) return;
    setLoading(true);
    try {
      const [allLots, codes, types, ...detailResults] = await Promise.all([
        lotsAPI.getAllLots(),
        riceCodesAPI.getAllRiceCodes(),
        riceCodesAPI.getRiceTypes(),
        ...isp.sauda_ids.map((saudaId) =>
          purchaseSummaryAPI
            .getKaantaPurchaseIspDetail(saudaId, isp.id, godownId)
            .catch(() => null)
        ),
      ]);
      setFullLotsList(allLots);
      setRiceCodes(codes);
      setRiceTypes(types);

      const mergedKaantas: Kaanta[] = [];
      const mergedLots: PurchaseSummaryLotDetail[] = [];
      for (const res of detailResults) {
        if (!res) continue;
        mergedKaantas.push(...res.kaantas);
        mergedLots.push(...res.lots);
      }
      setKaantas(mergeById(mergedKaantas));
      const uniqueLots = mergeById(mergedLots);
      // Match Purchases → Lots ordering where possible (API lots may omit created_at)
      const sorted = [...uniqueLots].sort((a, b) => {
        const la = allLots.find((x) => x.id === a.id);
        const lb = allLots.find((x) => x.id === b.id);
        if (la && lb) {
          return new Date(la.created_at).getTime() - new Date(lb.created_at).getTime();
        }
        return a.lot_number.localeCompare(b.lot_number);
      });
      setLots(sorted);
    } catch (error) {
      console.error('Failed to fetch data:', error);
    } finally {
      setLoading(false);
    }
  };

  const getRiceCodeName = (riceCodeId: string | null | undefined): string => {
    if (!riceCodeId) return 'N/A';
    const riceCode = riceCodes.find(rc => rc.rice_code_id === riceCodeId);
    return riceCode ? riceCode.rice_code_name : 'Unknown';
  };

  const openLotInNewTab = (lotId: string) => {
    // Open lots page with the specific lot in a new tab
    // Using URL params to potentially highlight/filter the lot
    window.open(`/purchases/lots?highlight=${lotId}`, '_blank');
  };

  const totalWeight = lots.reduce((sum, lot) => sum + (lot.received_weight || 0), 0);

  /** S. Nos. on Purchases → Lots (oldest-first), in the same order as the table below */
  const linkedLotSerials = useMemo(() => {
    return lots
      .map((lot) => getLotSerialNumberInFullPurchasesList(fullLotsList, lot.id))
      .filter((n): n is number => n != null);
  }, [lots, fullLotsList]);

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-40 bg-black/60 backdrop-blur-sm" />
        <Dialog.Content className="fixed left-[50%] top-[50%] z-50 w-[95vw] sm:w-[90vw] md:w-full max-w-2xl translate-x-[-50%] translate-y-[-50%]">
          <div className="glass rounded-xl sm:rounded-2xl p-4 sm:p-6 md:p-8 shadow-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-primary/20 rounded-lg">
                  <Package className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <Dialog.Title className="text-xl sm:text-2xl font-semibold">
                    Linked Lots
                  </Dialog.Title>
                  <Dialog.Description className="text-sm text-muted-foreground mt-1">
                    {isp?.slip_number} • {isp?.party_name}
                  </Dialog.Description>
                </div>
              </div>
              <button
                onClick={() => onOpenChange(false)}
                className="p-2 hover:bg-muted rounded-lg transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {loading ? (
              <div className="flex justify-center py-10">
                <LoadingSpinner />
              </div>
            ) : lots.length === 0 ? (
              <EmptyState 
                icon={Package} 
                title="No kaanta-linked lots" 
                description="No weighbridge-linked lots for this ISP (and godown scope, if set). Add a kaanta from Kaanta weight to create linked lots."
              />
            ) : (
              <>
                {/* Summary Stats */}
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div className="p-3 bg-muted/50 rounded-lg text-center min-w-0">
                    <div
                      className="text-base sm:text-lg font-bold text-primary tabular-nums leading-snug break-words"
                      title={linkedLotSerials.join(', ')}
                    >
                      {linkedLotSerials.length > 0 ? linkedLotSerials.join(', ') : '—'}
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">Lot Serial. Nos.</div>
                  </div>
                  <div className="p-3 bg-muted/50 rounded-lg text-center">
                    <div className="text-2xl font-bold text-primary">{totalWeight.toFixed(2)} kg</div>
                    <div className="text-xs text-muted-foreground">Total Weight</div>
                  </div>
                </div>

                {/* Kaantas Info */}
                {kaantas.length > 0 && (
                  <div className="mb-4 p-3 bg-blue-500/10 rounded-lg border border-blue-500/20">
                    <div className="text-sm font-medium text-blue-600 dark:text-blue-400 mb-1">
                      Kaanta Measurements: {kaantas.length}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      Total kaanta weight: {kaantas.reduce((sum, k) => sum + k.kaanta_weight, 0).toFixed(2)} kg
                    </div>
                  </div>
                )}

                {/* Lots Table */}
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border">
                        <th
                          className="text-left py-2 px-3 font-semibold w-14"
                          title="Matches S. No. on Purchases → Lots (all godowns, no search). Order: oldest first."
                        >
                          S. No.
                        </th>
                        <th className="text-left py-2 px-3 font-semibold">Lot Number</th>
                        <th className="text-left py-2 px-3 font-semibold">Rice</th>
                        <th className="text-right py-2 px-3 font-semibold">Bags</th>
                        <th className="text-right py-2 px-3 font-semibold">Weight</th>
                        <th className="text-right py-2 px-3 font-semibold">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {lots.map((lot) => {
                        const serial = getLotSerialNumberInFullPurchasesList(fullLotsList, lot.id);
                        return (
                        <tr key={lot.id} className="border-b border-border/60 hover:bg-muted/30">
                          <td
                            className="py-2 px-3 text-sm tabular-nums text-muted-foreground"
                            title="Serial by creation time (oldest = 1). Stays fixed when new lots are added."
                          >
                            {serial ?? '—'}
                          </td>
                          <td className="py-2 px-3">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span
                                className="font-mono text-xs text-muted-foreground"
                                title={lot.lot_number}
                              >
                                {getTruncatedLotNumberForDisplay(lot.lot_number)}
                              </span>
                              {isAutoGeneratedKaantaLot(lot as Lot) && (
                                <span className="text-[10px] px-1.5 py-0.5 bg-emerald-500/10 text-emerald-600 rounded">
                                  Auto
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="py-2 px-3">
                            <div className="text-xs">
                              <div>{getRiceCodeName(lot.rice_code_id)}</div>
                              <div className="text-muted-foreground">
                                {getRiceTypeLabel(lot.rice_type, riceTypes) || '-'}
                              </div>
                            </div>
                          </td>
                          <td className="py-2 px-3 text-right">{lot.no_of_bags}</td>
                          <td className="py-2 px-3 text-right">{lot.received_weight.toFixed(2)} kg</td>
                          <td className="py-2 px-3 text-right">
                            <button
                              onClick={() => openLotInNewTab(lot.id)}
                              className="p-1.5 hover:bg-muted rounded-lg transition-colors inline-flex items-center gap-1 text-primary"
                              title="Open in Lots page"
                            >
                              <ExternalLink className="h-4 w-4" />
                            </button>
                          </td>
                        </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>

                <div className="flex justify-end gap-3 pt-6">
                  <button
                    onClick={() => window.open('/purchases/lots', '_blank')}
                    className="px-4 py-2 border border-border rounded-lg hover:bg-muted transition-colors inline-flex items-center gap-2"
                  >
                    <ExternalLink className="h-4 w-4" />
                    Open Lots Page
                  </button>
                  <button
                    onClick={() => onOpenChange(false)}
                    className="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
                  >
                    Close
                  </button>
                </div>
              </>
            )}
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

