import type { Lot } from '../types/entities';

/** Prefer ISP creation time for display/sort when the API provides it. */
export function getLotDisplayDateIso(lot: Lot): string {
  const isp = lot.inward_slip_pass_created_at?.trim();
  if (isp) return isp;
  return lot.created_at;
}

export function isAutoGeneratedKaantaLot(lot: Lot): boolean {
  return lot.lot_number.startsWith('LOT-KAANTA-');
}

/** Short label for LOT-KAANTA-* and other lot numbers (Lots table, Linked Lots). Full value via copy / title. */
export function getTruncatedLotNumberForDisplay(lotNumber: string): string {
  if (lotNumber.startsWith('LOT-KAANTA-')) {
    const idPart = lotNumber.replace('LOT-KAANTA-', '');
    return `LOT-KAANTA-${idPart.slice(0, 6)}...`;
  }
  return lotNumber.length > 10 ? `${lotNumber.slice(0, 10)}...` : lotNumber;
}

/**
 * Stable display order: oldest first → new lots always appear at the bottom.
 * S. No. = position in this order (1-based) and does not reshuffle when new lots are added.
 */
export function sortLotsByCreatedAtAsc(lots: Lot[]): Lot[] {
  return [...lots].sort((a, b) => {
    const ta = new Date(getLotDisplayDateIso(a)).getTime();
    const tb = new Date(getLotDisplayDateIso(b)).getTime();
    if (ta !== tb) return ta - tb;
    return a.id.localeCompare(b.id);
  });
}

/** Persistent S. No. for lots: 1-based index in the full list after `sortLotsByCreatedAtAsc` */
export function getLotSerialNumberInFullPurchasesList(fullList: Lot[], lotId: string): number | null {
  const sorted = sortLotsByCreatedAtAsc(fullList);
  const i = sorted.findIndex((l) => l.id === lotId);
  return i >= 0 ? i + 1 : null;
}
