import { useState, useMemo, useEffect } from 'react';
import { SearchBar } from '../../admin/shared/SearchBar';
import { LoadingSpinner } from '../../admin/shared/LoadingSpinner';
import { EmptyState } from '../../admin/shared/EmptyState';
import { ActionButtons } from '../../admin/shared/ActionButtons';
import { ConfirmDialog } from '../../admin/shared/ConfirmDialog';
import { Package, Info } from 'lucide-react';
import { useLots } from '../../../hooks/useLots';
import { riceCodesAPI } from '../../../services/riceCodes.api';
import { getRiceTypeLabel } from '../../../utils/riceType';
// LotFormModal import removed - edit functionality disabled
// import { LotFormModal } from './LotFormModal';
import { LotPreviewDialog } from './LotPreviewDialog';
import type { Lot, RiceCode, RiceType } from '../../../types/entities';

export function LotsTable() {
  const [saudaFilter, setSaudaFilter] = useState<string | undefined>();
  const { lots, loading, deleteLot, refetch } = useLots(saudaFilter);
  const [searchQuery, setSearchQuery] = useState('');
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [selectedLot, setSelectedLot] = useState<Lot | null>(null);
  // NOTE: Manual lot creation and editing have been disabled. Lots are now auto-created via Kaanta.
  // const [createOpen, setCreateOpen] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewLot, setPreviewLot] = useState<Lot | null>(null);
  const [riceCodes, setRiceCodes] = useState<RiceCode[]>([]);
  const [riceTypes, setRiceTypes] = useState<RiceType[]>([]);

  useEffect(() => {
    const fetchRiceCodes = async () => {
      try {
        const data = await riceCodesAPI.getAllRiceCodes();
        setRiceCodes(data);
      } catch (error) {
        console.error('Failed to fetch rice codes:', error);
      }
    };
    const fetchRiceTypes = async () => {
      try {
        const data = await riceCodesAPI.getRiceTypes();
        setRiceTypes(data);
      } catch (error) {
        console.error('Failed to fetch rice types:', error);
      }
    };
    fetchRiceCodes();
    fetchRiceTypes();
  }, []);

  const getRiceCodeName = (riceCodeId: string | null | undefined): string => {
    if (!riceCodeId) return '';
    const riceCode = riceCodes.find((rc) => rc.rice_code_id === riceCodeId);
    return riceCode ? riceCode.rice_code_name : '';
  };

  const getLotDisplayName = (lot: Lot): string => {
    const parts: string[] = [];
    
    const riceCodeName = getRiceCodeName(lot.rice_code_id);
    if (riceCodeName) parts.push(riceCodeName);
    
    const riceTypeLabel = getRiceTypeLabel(lot.rice_type, riceTypes);
    if (riceTypeLabel) parts.push(riceTypeLabel);
    
    return parts.join(' - ') || 'Lot';
  };

  const filtered = useMemo(() => {
    return lots.filter((lot) => {
      const q = searchQuery.toLowerCase();
      const displayName = getLotDisplayName(lot).toLowerCase();
      const riceCodeName = getRiceCodeName(lot.rice_code_id).toLowerCase();
      const riceTypeLabel = getRiceTypeLabel(lot.rice_type, riceTypes).toLowerCase();
      const matchesSearch =
        lot.lot_number.toLowerCase().includes(q) ||
        displayName.includes(q) ||
        riceCodeName.includes(q) ||
        riceTypeLabel.includes(q);

      return matchesSearch;
    });
  }, [lots, searchQuery, riceCodes, riceTypes]);

  // Helper to check if a lot was auto-generated via Kaanta
  const isAutoGeneratedLot = (lot: Lot): boolean => {
    return lot.lot_number.startsWith('LOT-KAANTA-');
  };

  return (
    <div>
      {/* Info banner about auto-lot creation */}
      <div className="mb-6 p-3 bg-blue-500/10 border border-blue-500/20 rounded-lg flex gap-3">
        <Info className="h-5 w-5 text-blue-500 flex-shrink-0 mt-0.5" />
        <div className="text-sm text-blue-600 dark:text-blue-400">
          <p className="font-medium">Lots are now auto-created</p>
          <p className="text-xs mt-1 text-muted-foreground">
            Lots are automatically created when you add a Kaanta measurement in the Inward Slip Passes module.
            You can still delete existing lots here.
          </p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-3 mb-6">
        <div className="flex-1 min-w-0">
          <SearchBar value={searchQuery} onChange={setSearchQuery} placeholder="Search by lot number, rice code or type..." />
        </div>
        {/* Add Lot button commented out - lots are now auto-created via Kaanta */}
        {/*
        <div className="flex gap-2">
          <button
            onClick={() => setCreateOpen(true)}
            className="btn-primary rounded-xl inline-flex items-center justify-center gap-2 px-4 py-2"
          >
            Add Lot
          </button>
        </div>
        */}
      </div>

      {loading ? (
        <div className="flex justify-center py-20"><LoadingSpinner /></div>
      ) : filtered.length === 0 ? (
        <EmptyState 
          icon={Package} 
          title="No lots found" 
          description="Lots will appear here when you create Kaanta measurements in the ISP module."
        />
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-border">
                <th className="text-left py-3 px-4 text-sm font-semibold">Lot Number</th>
                <th className="text-left py-3 px-4 text-sm font-semibold">Rice Code / Type</th>
                <th className="text-right py-3 px-4 text-sm font-semibold">Bags</th>
                <th className="text-right py-3 px-4 text-sm font-semibold">Bill Weight</th>
                <th className="text-right py-3 px-4 text-sm font-semibold">Received Weight</th>
                <th className="text-right py-3 px-4 text-sm font-semibold">Rate</th>
                <th className="text-right py-3 px-4 text-sm font-semibold">Amount</th>
                <th className="text-right py-3 px-4 text-sm font-semibold">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((lot) => (
                <tr key={lot.id} className="border-b border-border/60 hover:bg-muted/30 transition-colors">
                  <td className="py-3 px-4">
                    <div className="flex items-center gap-2">
                      <Package className="h-4 w-4 text-primary" />
                      <span className="text-sm font-medium">{lot.lot_number}</span>
                      {isAutoGeneratedLot(lot) && (
                        <span className="text-[10px] px-1.5 py-0.5 bg-emerald-500/10 text-emerald-600 rounded">
                          Auto
                        </span>
                      )}
                    </div>
                  </td>
                  <td className="py-3 px-4">
                    <div className="text-sm">
                      <div className="font-medium">{getRiceCodeName(lot.rice_code_id) || '-'}</div>
                      <div className="text-xs text-muted-foreground">
                        {getRiceTypeLabel(lot.rice_type, riceTypes) || '-'}
                      </div>
                    </div>
                  </td>
                  <td className="py-3 px-4 text-right text-sm">{lot.no_of_bags}</td>
                  <td className="py-3 px-4 text-right text-sm">{lot.bill_weight} kg</td>
                  <td className="py-3 px-4 text-right text-sm">{lot.received_weight.toFixed(2)} kg</td>
                  <td className="py-3 px-4 text-right text-sm">₹{(lot.rate ?? 0).toFixed(2)}</td>
                  <td className="py-3 px-4 text-right text-sm font-medium">₹{(lot.amount ?? 0).toFixed(2)}</td>
                  <td className="py-3 px-4">
                    <div className="flex items-center justify-end gap-2">
                      <button
                        onClick={() => {
                          setPreviewLot(lot);
                          setPreviewOpen(true);
                        }}
                        className="text-xs text-primary hover:text-primary/80 px-2 py-1 rounded hover:bg-primary/10 transition-colors"
                      >
                        View
                      </button>
                      <ActionButtons
                        isActive={true}
                        onDelete={() => {
                          setSelectedLot(lot);
                          setDeleteDialogOpen(true);
                        }}
                        permissionEntity="vendor"
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <ConfirmDialog
        open={deleteDialogOpen}
        onOpenChange={setDeleteDialogOpen}
        onConfirm={async () => {
          if (selectedLot) {
            await deleteLot(selectedLot.id);
            setDeleteDialogOpen(false);
            setSelectedLot(null);
          }
        }}
        title="Delete Lot"
        description={`Are you sure you want to delete ${selectedLot?.lot_number}? This action cannot be undone.`}
        confirmText="Delete"
      />

      {/* Create and edit modals disabled - lots are now auto-created via Kaanta and cannot be edited
      <LotFormModal
        open={createOpen}
        onOpenChange={(open) => {
          setCreateOpen(open);
          if (!open) {
            refetch();
          }
        }}
      />
      <LotFormModal
        open={editModalOpen}
        onOpenChange={(open) => {
          setEditModalOpen(open);
          if (!open) {
            setSelectedLotId(null);
            refetch();
          }
        }}
        lotId={selectedLotId}
      />
      */}

      <LotPreviewDialog
        open={previewOpen}
        onOpenChange={setPreviewOpen}
        lot={previewLot}
      />
    </div>
  );
}

